In [2]:
import pandas as pd
import csv

from pandas.errors import ParserError


try:
    df = pd.read_csv('https://opendata.caissedesdepots.fr/api/explore/v2.1/catalog/datasets/moncompteformation_catalogueformation/exports/csv?limit=100&timezone=UTC&use_labels=false&epsg=4326', sep=";")
except ParserError:
    pass

df.head(100)

,date_extract,nom_of,nom_departement,nom_region,type_referentiel,code_inventaire,code_rncp,intitule_certification,libelle_niveau_sortie_formation,code_formacode_1,...,nombre_heures_total_min,nombre_heures_total_max,nombre_heures_total_mean,frais_ttc_tot_min,frais_ttc_tot_max,frais_ttc_tot_mean,code_departement,code_region,nbaction_nbheures,coderegion_export
0,2024-07-10,A+CONSEILS,Vendée,Pays de la Loire,RS,5081,-1,Certificat d'aptitude à conduire en sécurité (...,NaN,31717.0,...,21,21,21,744.0,744.0,744.0,85.0,52.0,21,52.0
1,2024-07-10,A+CONSEILS,Vendée,Pays de la Loire,RS,5084,-1,Certificat d'aptitude à conduire en sécurité (...,NaN,31715.0,...,0,0,0,1044.0,1044.0,1044.0,85.0,52.0,0,52.0
2,2024-07-10,A+CONSEILS,Vendée,Pays de la Loire,RS,5084,-1,Certificat d'aptitude à conduire en sécurité (...,NaN,31715.0,...,0,0,0,720.0,720.0,720.0,85.0,52.0,0,52.0
3,2024-07-10,A-Z Linguistics,Yvelines,Île-de-France,RS,6435,-1,Certification CLOE anglais,NaN,15234.0,...,0,0,0,3168.0,3960.0,3564.0,78.0,11.0,0,11.0
4,2024-07-10,A. DOC,NaN,NaN,RS,6029,-1,Conception de maquettes numériques architectur...,NaN,22252.0,...,28,28,28,4200.0,4200.0,4200.0,NaN,NaN,28,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-07-10,ABC FORMATION,Savoie,Auvergne-Rhône-Alpes,RS,5099,-1,Certificat d'aptitude à conduire en sécurité (...,NaN,31717.0,...,35,35,35,1680.0,1680.0,1680.0,73.0,84.0,35,84.0
96,2024-07-10,ABC FORMATION,Savoie,Auvergne-Rhône-Alpes,RS,5101,-1,Certificat d'aptitude à conduire en sécurité (...,NaN,31717.0,...,14,14,14,651.6,651.6,651.6,73.0,84.0,14,84.0
97,2024-07-10,ABC FORMATION,Savoie,Auvergne-Rhône-Alpes,RS,5109,-1,Certificat d'aptitude à conduire en sécurité (...,NaN,31768.0,...,14,14,14,516.0,516.0,516.0,73.0,84.0,14,84.0
98,2024-07-10,ABC FORMATION,Savoie,Auvergne-Rhône-Alpes,RS,5084,-1,Certificat d'aptitude à conduire en sécurité (...,NaN,31715.0,...,21,21,21,954.0,954.0,954.0,73.0,84.0,21,84.0
99,2024-07-10,ABC FORMATION CONTINUE,Territoire de Belfort,Bourgogne-Franche-Comté,RS,6436,-1,Certification CLOE allemand,NaN,15287.0,...,0,0,0,1482.5,1482.5,1482.5,90.0,27.0,0,27.0

load test sur 100 lignes

In [3]:
df_test = pd.read_csv('https://opendata.caissedesdepots.fr/api/explore/v2.1/catalog/datasets/moncompteformation_catalogueformation/exports/csv?limit=100&timezone=UTC&use_labels=false&epsg=4326', sep=";")

In [4]:
nb = df_test.count()
print(nb)

date_extract                        100
nom_of                              100
nom_departement                      90
nom_region                           90
type_referentiel                    100
code_inventaire                     100
code_rncp                           100
intitule_certification              100
libelle_niveau_sortie_formation      14
code_formacode_1                     98
code_formacode_2                     68
code_formacode_3                      7
code_formacode_4                      0
code_formacode_5                      0
libelle_code_formacode_principal     98
code_rome_1                          14
code_rome_2                           5
code_rome_3                           3
code_rome_4                           3
code_rome_5                           1
libelle_nsf_1                       100
libelle_nsf_2                         5
libelle_nsf_3                         2
code_nsf_1                          100
code_nsf_2                            5
code_nsf_3                            2
code_certifinfo                     100
siret                               100
numero_formation                    100
intitule_formation                  100
points_forts                        100
nb_action                           100
nb_session_active                   100
nb_session_a_distance               100
nombre_heures_total_min             100
nombre_heures_total_max             100
nombre_heures_total_mean            100
frais_ttc_tot_min                   100
frais_ttc_tot_max                   100
frais_ttc_tot_mean                  100
code_departement                     90
code_region                          90
nbaction_nbheures                   100
coderegion_export                    90
dtype: int64

In [5]:
df_test.columns

Index(['date_extract', 'nom_of', 'nom_departement', 'nom_region',
       'type_referentiel', 'code_inventaire', 'code_rncp',
       'intitule_certification', 'libelle_niveau_sortie_formation',
       'code_formacode_1', 'code_formacode_2', 'code_formacode_3',
       'code_formacode_4', 'code_formacode_5',
       'libelle_code_formacode_principal', 'code_rome_1', 'code_rome_2',
       'code_rome_3', 'code_rome_4', 'code_rome_5', 'libelle_nsf_1',
       'libelle_nsf_2', 'libelle_nsf_3', 'code_nsf_1', 'code_nsf_2',
       'code_nsf_3', 'code_certifinfo', 'siret', 'numero_formation',
       'intitule_formation', 'points_forts', 'nb_action', 'nb_session_active',
       'nb_session_a_distance', 'nombre_heures_total_min',
       'nombre_heures_total_max', 'nombre_heures_total_mean',
       'frais_ttc_tot_min', 'frais_ttc_tot_max', 'frais_ttc_tot_mean',
       'code_departement', 'code_region', 'nbaction_nbheures',
       'coderegion_export'],
      dtype='object')

In [6]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 44 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   date_extract                      100 non-null    object
 1   nom_of                            100 non-null    object
 2   nom_departement                   90 non-null     object
 3   nom_region                        90 non-null     object
 4   type_referentiel                  100 non-null    object
 5   code_inventaire                   100 non-null    int64
 6   code_rncp                         100 non-null    int64
 7   intitule_certification            100 non-null    object
 8   libelle_niveau_sortie_formation   14 non-null     object
 9   code_formacode_1                  98 non-null     float64
 10  code_formacode_2                  68 non-null     float64
 11  code_formacode_3                  7 non-null      float64
 12  code_formacode_4                  0 non-null      float64
 13  code_formacode_5                  0 non-null      float64
 14  libelle_code_formacode_principal  98 non-null     object
 15  code_rome_1                       14 non-null     object
 16  code_rome_2                       5 non-null      object
 17  code_rome_3                       3 non-null      object
 18  code_rome_4                       3 non-null      object
 19  code_rome_5                       1 non-null      object
 20  libelle_nsf_1                     100 non-null    object
 21  libelle_nsf_2                     5 non-null      object
 22  libelle_nsf_3                     2 non-null      object
 23  code_nsf_1                        100 non-null    int64
 24  code_nsf_2                        5 non-null      float64
 25  code_nsf_3                        2 non-null      float64
 26  code_certifinfo                   100 non-null    int64
 27  siret                             100 non-null    int64
 28  numero_formation                  100 non-null    object
 29  intitule_formation                100 non-null    object
 30  points_forts                      100 non-null    object
 31  nb_action                         100 non-null    int64
 32  nb_session_active                 100 non-null    int64
 33  nb_session_a_distance             100 non-null    int64
 34  nombre_heures_total_min           100 non-null    int64
 35  nombre_heures_total_max           100 non-null    int64
 36  nombre_heures_total_mean          100 non-null    int64
 37  frais_ttc_tot_min                 100 non-null    float64
 38  frais_ttc_tot_max                 100 non-null    float64
 39  frais_ttc_tot_mean                100 non-null    float64
 40  code_departement                  90 non-null     float64
 41  code_region                       90 non-null     float64
 42  nbaction_nbheures                 100 non-null    int64
 43  coderegion_export                 90 non-null     float64
dtypes: float64(13), int64(12), object(19)
memory usage: 34.5+ KB

load integral du dataset

In [7]:
df_load = pd.read_csv('https://opendata.caissedesdepots.fr/api/explore/v2.1/catalog/datasets/moncompteformation_catalogueformation/exports/csv?limit=-1&timezone=UTC&use_labels=false&epsg=4326', sep=";")

/tmp/ipykernel_230957/3757554394.py:1: DtypeWarning: Columns (41,43) have mixed types. Specify dtype option on import or set low_memory=False.
  df_load = pd.read_csv('https://opendata.caissedesdepots.fr/api/explore/v2.1/catalog/datasets/moncompteformation_catalogueformation/exports/csv?limit=-1&timezone=UTC&use_labels=false&epsg=4326', sep=";")

In [8]:
df_load.count()

date_extract                        168201
nom_of                              165027
nom_departement                     131527
nom_region                          131527
type_referentiel                    168201
code_inventaire                     168201
code_rncp                           168201
intitule_certification              168201
libelle_niveau_sortie_formation      40220
code_formacode_1                    165019
code_formacode_2                    100546
code_formacode_3                     21606
code_formacode_4                      8100
code_formacode_5                      2231
libelle_code_formacode_principal    165019
code_rome_1                          40976
code_rome_2                          20868
code_rome_3                          12357
code_rome_4                           8237
code_rome_5                           4682
libelle_nsf_1                       168197
libelle_nsf_2                        27727
libelle_nsf_3                         4536
code_nsf_1                          168197
code_nsf_2                           27727
code_nsf_3                            4536
code_certifinfo                     168201
siret                               168201
numero_formation                    168201
intitule_formation                  168201
points_forts                        167984
nb_action                           168201
nb_session_active                   168201
nb_session_a_distance               168201
nombre_heures_total_min             168201
nombre_heures_total_max             168201
nombre_heures_total_mean            168201
frais_ttc_tot_min                   168201
frais_ttc_tot_max                   168201
frais_ttc_tot_mean                  168201
code_departement                    131547
code_region                         131547
nbaction_nbheures                   168201
coderegion_export                   131547
dtype: int64

load certif formation 1007 avant 12h35
=>determiner la frequence des mises a jour et faire un choix pour la maj bases de données via requete api

In [46]:
df_load.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212930 entries, 0 to 212929
Data columns (total 44 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   date_extract                      212930 non-null  object
 1   nom_of                            208909 non-null  object
 2   nom_departement                   166014 non-null  object
 3   nom_region                        166014 non-null  object
 4   type_referentiel                  212930 non-null  object
 5   code_inventaire                   212930 non-null  int64
 6   code_rncp                         212930 non-null  int64
 7   intitule_certification            212930 non-null  object
 8   libelle_niveau_sortie_formation   51290 non-null   object
 9   code_formacode_1                  208231 non-null  float64
 10  code_formacode_2                  126445 non-null  float64
 11  code_formacode_3                  27332 non-null   float64
 12  code_formacode_4                  10430 non-null   float64
 13  code_formacode_5                  2935 non-null    float64
 14  libelle_code_formacode_principal  208231 non-null  object
 15  code_rome_1                       52269 non-null   object
 16  code_rome_2                       27356 non-null   object
 17  code_rome_3                       16771 non-null   object
 18  code_rome_4                       11437 non-null   object
 19  code_rome_5                       6504 non-null    object
 20  libelle_nsf_1                     212925 non-null  object
 21  libelle_nsf_2                     36278 non-null   object
 22  libelle_nsf_3                     6301 non-null    object
 23  code_nsf_1                        212925 non-null  float64
 24  code_nsf_2                        36278 non-null   float64
 25  code_nsf_3                        6301 non-null    float64
 26  code_certifinfo                   212930 non-null  int64
 27  siret                             212930 non-null  int64
 28  numero_formation                  212930 non-null  object
 29  intitule_formation                212930 non-null  object
 30  points_forts                      212661 non-null  object
 31  nb_action                         212930 non-null  int64
 32  nb_session_active                 212930 non-null  int64
 33  nb_session_a_distance             212930 non-null  int64
 34  nombre_heures_total_min           212930 non-null  int64
 35  nombre_heures_total_max           212930 non-null  int64
 36  nombre_heures_total_mean          212930 non-null  int64
 37  frais_ttc_tot_min                 212930 non-null  float64
 38  frais_ttc_tot_max                 212930 non-null  float64
 39  frais_ttc_tot_mean                212930 non-null  float64
 40  code_departement                  166034 non-null  object
 41  code_region                       166034 non-null  object
 42  nbaction_nbheures                 212930 non-null  int64
 43  coderegion_export                 166034 non-null  object
dtypes: float64(11), int64(11), object(22)
memory usage: 71.5+ MB

suppression des colonnes non selectionnées pour la comparaison

ciblage des formations similaires a simplon (codes nfs formacodes?)
=> laetitia : need of a liste of nfs1 ou autres différenciant == filtre sur dataframe